/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CompetenceIcon: typeof import('./src/components/Sections/CompetenceIcon.vue')['default']
    CompetenceIcone: typeof import('./src/components/Sections/CompetenceIcone.vue')['default']
    Competences: typeof import('./src/components/Sections/Competences.vue')['default']
    CompetenceTitle: typeof import('./src/components/Sections/CompetenceTitle.vue')['default']
    Cover: typeof import('./src/components/Cover.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Sections: typeof import('./src/components/Sections.vue')['default']
    SectionTitle: typeof import('./src/components/Sections/SectionTitle.vue')['default']
    Title: typeof import('./src/components/Sections/Title.vue')['default']
  }
}
