/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CompetenceIcone: typeof import('./src/components/Sections/CompetenceIcone.vue')['default']
    Competences: typeof import('./src/components/Sections/Competences.vue')['default']
    CompetenceTitle: typeof import('./src/components/Sections/CompetenceTitle.vue')['default']
    ContactIcone: typeof import('./src/components/Sections/Contacts/ContactIcone.vue')['default']
    Cover: typeof import('./src/components/Cover.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icone: typeof import('./src/components/Sections/Contacts/Icone.vue')['default']
    Item: typeof import('./src/components/Sections/Projets/Item.vue')['default']
    Main: typeof import('./src/components/Sections/Contacts/Main.vue')['default']
    ProjetItem: typeof import('./src/components/Sections/Projets/ProjetItem.vue')['default']
    ProjetMain: typeof import('./src/components/Sections/Projets/ProjetMain.vue')['default']
    Sections: typeof import('./src/components/Sections.vue')['default']
    SectionTitle: typeof import('./src/components/Sections/SectionTitle.vue')['default']
  }
}
